<h2>List of Payment Methods</h2>
<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
    
	  	<tr>
		    <th>No</th>
		    <th>Payment Method</th>
	    </tr>
    </thead>
    <?php
	$result = $block->getPaymentMethod();
	
	echo "<pre>";
	print_r($result);
    echo "</pre>";
    die();
	$stt = 0;
	foreach($result as $value){
		if(isset($value['title'])){
			$stt++;
			echo "<tr style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">";
			echo "<td>$stt</td>";
			echo "<td>".$value['title']."</td>";
			echo "</tr>";
		}
		
	}


	// echo $result['model'];
	
	
    ?>
</table>