<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <h1>Lorem</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero asperiores dignissimos natus architecto, voluptatum beatae ipsum sequi, quas dolorem voluptatibus modi officiis provident ducimus deleniti optio earum minus? Voluptate, molestiae.</p>
    </div>
</body>
</html>